### ISSUE TITLE
App Update Behavior: App crashed on the phone and Preset Customizations didn't retain on the tablet 

### ISSUE THREAD

**Issue by CananArikan** [willowtreeapps/vocable-android#387]
**Describe the bug**
**Tablet**: After the upgrade app on the Galaxy S6 tablet, custom categories and phrases are retained as before. Timing and sensitivity settings are retained as before. But preset categories’ customization didn’t retain. All presets are updated as a fresh new install.
**Phone**: While trying to upgrade the app on the Galaxy S8 Phone, the `Vocable keeps stopping` error occurred and the app crashed.

**To Reproduce**
Before updating the app, 

1. Add a custom category and phrase
2. Hide a category
3. Reorder a category
4. Update hover time
5. Update sensitivity
6. Update the app

**Expected behavior**
1. Custom categories and phrases still exist
2. Hidden category is still hidden
3. Category reordering is preserved
4. Hover time is same as before
5. Sensitivity is same as before
6. All other presets and unchanged categories remain as before

**Actual Behavior**
**Tablet**: Custom categories and phrases are retained as before. Timing and sensitivity settings are retained as before. But preset categories’ customization didn’t retain. All presets are updated as a fresh new install.
**Phone**: `Vocable keeps stopping` error occurred and the app crashed.

**Devices:**
**Tablet**: Galaxy S6 tablet - Android 12
**Phone**: Galaxy S8 Phone - Android 9

**Comment by PaulKlauser** [comment]
Since artifacts of old builds weren't being saved anywhere, had to do some archaeological work to get a pseudo-1.5.2 build to be able to reproduce this bug. The branch for creating that build is: `experiment/attempt-to-build-1.5.2`.

Upgrading from a release build on that branch to a release build from main persists all settings and categories **except**, the phrases in the categories don't seem to migrate. Further investigation needed.

**Comment by PaulKlauser** [comment]
Going to skip having someone manually validate upgrade path until we're ready to ship, since there are more schema changes coming.
